trigger:
  - main
  - develop

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    jobs:
      - job: PrepareMatrix
        steps:
          - script: |
              echo '[{"name":"a"},{"name":"b"}]' > matrix.json
              cat matrix.json
              echo "##vso[task.setvariable variable=jobMatrix;isoutput=true]$(cat matrix.json)"
            name: "matrix"

      - job: BuildJob
        dependsOn: PrepareMatrix
        strategy:
          matrix: $[ dependencies.PrepareMatrix.outputs['matrix.jobMatrix'] ]

        steps:
          - bash: |
              echo "This is job $(name)."
              echo "##vso[task.setvariable variable=jobResult;isoutput=true]Succeeded"
            name: SetResult

      - job: DeployJob
        dependsOn: BuildJob
        condition: eq(dependencies.BuildJob.outputs['$(name).SetResult.jobResult'], 'Succeeded')
        strategy:
          matrix:
            a:
              name: a
            b:
              name: b

        steps:
          - script: |
              echo $(name)
            displayName: "simple echo"
