trigger:
  - main
  - develop

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    jobs:
      - job: PrepareMatrix
        steps:
          - bash: |
              echo "##vso[task.setVariable variable=jobMatrix;isOutput=true]{'a':{'name':'a'}, 'b':{'name':'b'}}"
            name: "matrix"

      - job: BuildJob
        dependsOn: PrepareMatrix
        strategy:
          matrix: $[ dependencies.PrepareMatrix.outputs['matrix.jobMatrix'] ]

        steps:
          - bash: |
              echo "This is job $(name)."
              echo "##vso[task.setvariable variable=jobResult;isoutput=true]Succeeded"
            name: SetResult

      - job: DeployJob
        dependsOn: BuildJob
        condition: eq(dependencies.BuildJob.outputs['a.SetResult.jobResult'], 'Succeeded')
        strategy:
          matrix:
            ${{ each job independencies.PrepareMatrix.outputs['matrix.jobMatrix'] }}:
              ${{ job.name }}:
                name: ${{ job.name }}

        steps:
          - script: |
              echo $(name)
            displayName: "simple echo"
