trigger:
  - main
  - develop

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        strategy:
          matrix:
            a:
              name: a
            b:
              name: b

        steps:
          - script: |
              echo $(name)
            displayName: "simple echo"

          - bash: |
              echo "This is job Foo."
              echo "##vso[task.setvariable variable=jobResult;isoutput=true]Succeeded"
            name: SetResult

      - job: DeployJob
        dependsOn: BuildJob
        variables:
          resultVar: $[ dependencies.BuildJob.outputs['a.SetResult.jobResult'] ]
        condition: eq(variables['resultVar'], 'Succeeded')
        strategy:
          matrix:
            a:
              name: a
            b:
              name: b

        steps:
          - script: |
              echo $(name)
            displayName: "simple echo"
