trigger:
  - main
  - develop

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        strategy:
          matrix:
            a:
              name: a
            b:
              name: b

        steps:
          - script: |
              echo $(name)
            displayName: "simple echo"

          - bash: |
              echo "This is job Foo."
              echo "##vso[task.setvariable variable=Result;isOutput=true]Succeeded" #set variable Result to Succeeded
            name: result

      - job: DeployJob
        dependsOn: BuildJob
        condition: eq(dependencies.BuildJob.outputs['a_result.Result'], 'Succeeded')
        strategy:
          matrix:
            a:
              name: a
            b:
              name: b

        steps:
          - script: |
              echo $(name)
            displayName: "simple echo"
